#!/usr/bin/env python3
"""
Redfin House Fetcher for House Scorer
=====================================
Run this locally on your machine to pull listings from Redfin's API.

Usage:
  pip install redfin requests
  python redfin_fetcher.py --town "Milton, MA" --min-price 700000 --max-price 1400000
  python redfin_fetcher.py --url "https://www.redfin.com/MA/Milton/123-Main-St/home/12345"
  python redfin_fetcher.py --towns-file towns.txt --min-price 700000 --max-price 1400000

Output:
  Creates a JSON file (redfin_listings.json) that you can import into the House Scorer app.
"""

import argparse
import csv
import io
import json
import os
import re
import sys
import time
from datetime import datetime

try:
    import requests
except ImportError:
    print("ERROR: 'requests' package not installed. Run: pip install requests")
    sys.exit(1)

# Fix SSL certificate verification issues (common on macOS)
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


# ===== TOWN ID MAPPING =====
# Redfin region IDs for MA towns (from redfin.com/city/{id}/MA/{name})
REDFIN_REGIONS = {
    "Newton": 11619, "Arlington": 36088, "Belmont": 36093, "Milton": 36138,
    "Dedham": 36104, "Needham": 36141, "Wellesley": 36180, "Hingham": 36118,
    "Watertown": 29540, "Westwood": 29720, "Natick": 29757, "Duxbury": 36107,
    "Franklin": 29779, "Scituate": 36163, "Quincy": 14424, "Canton": 29589,
    "Hanover": 29713, "Waltham": 18529, "Braintree": 29818, "Walpole": 36175,
    "Medfield": 36135, "Dover": 36106, "Weston": 29572, "Norwood": 36145,
    "Norfolk": 29591, "Cohasset": 29606, "Sharon": 36164, "Foxborough": 36113,
    "Sherborn": 29708, "Marshfield": 36133, "Medway": 29802, "Randolph": 36154,
    "Mansfield": 29673, "Weymouth": 35857, "Holliston": 29682, "Rockland": 29581,
    "Bridgewater": 36097, "Avon": 29667, "Hopkinton": 36122, "Framingham": 36114,
    "Hull": 36124, "Abington": 36085, "Norwell": 29770, "Ashland": 29747,
    "Whitman": 29741, "Millis": 29670, "Holbrook": 36119, "Stoughton": 29791,
    "Grafton": 29762, "Easton": 29538, "Plainville": 29561, "Wrentham": 29552,
    "Upton": 36173, "Raynham": 29812, "Attleboro": 710, "Bellingham": 36092,
}

# ===== TOWN TIERS (loaded dynamically from town_scores_compact.json) =====
# Looks for the JSON file next to this script, or in the current directory.
# If not found, falls back to a hardcoded tier list.

def _load_town_tiers():
    """Load tier assignments from town_scores_compact.json (generated by Town Ranker)."""
    # Search for the JSON file in likely locations
    search_paths = [
        os.path.join(os.path.dirname(os.path.abspath(__file__)), 'town_scores_compact.json'),
        os.path.join(os.getcwd(), 'town_scores_compact.json'),
    ]
    for path in search_paths:
        if os.path.exists(path):
            try:
                with open(path) as f:
                    scores = json.load(f)
                tiers = {}
                for _id, info in scores.items():
                    tier = info.get('tier', '?')
                    name = info.get('name', _id.title())
                    if tier not in tiers:
                        tiers[tier] = []
                    tiers[tier].append(name)
                # Sort towns within each tier by composite score (highest first)
                for tier in tiers:
                    tiers[tier].sort(key=lambda n: next(
                        (v['composite'] for v in scores.values() if v['name'] == n), 0
                    ), reverse=True)
                print(f"  Loaded tiers from: {path}")
                return tiers
            except Exception as e:
                print(f"  Warning: Could not parse {path}: {e}")

    # Fallback: hardcoded tiers
    print("  Note: town_scores_compact.json not found, using built-in tier list.")
    return {
        'S': ['Newton', 'Arlington', 'Belmont', 'Milton'],
        'A': ['Dedham', 'Needham', 'Wellesley'],
        'B': ['Hingham', 'Watertown', 'Westwood', 'Natick', 'Duxbury', 'Franklin', 'Scituate',
              'Quincy', 'Canton', 'Hanover', 'Waltham', 'Braintree', 'Walpole', 'Medfield'],
        'C': ['Dover', 'Weston', 'Norwood', 'Norfolk', 'Cohasset', 'Sharon', 'Foxborough',
              'Sherborn', 'Marshfield', 'Medway', 'Randolph', 'Mansfield', 'Weymouth',
              'Holliston', 'Rockland', 'Bridgewater', 'Avon', 'Hopkinton'],
        'D': ['Framingham', 'Hull', 'Abington', 'Norwell', 'Ashland', 'Whitman', 'Millis',
              'Holbrook', 'Stoughton', 'Grafton', 'Easton', 'Plainville'],
        'E': ['Wrentham', 'Upton', 'Raynham'],
        'F': ['Attleboro', 'Bellingham'],
    }


TOWN_TIERS = None  # loaded lazily on first use


def get_towns_for_tiers(tiers):
    """Return list of town names for the given tier letters."""
    global TOWN_TIERS
    if TOWN_TIERS is None:
        TOWN_TIERS = _load_town_tiers()
    towns = []
    for t in tiers:
        t_upper = t.upper()
        if t_upper in TOWN_TIERS:
            towns.extend(TOWN_TIERS[t_upper])
        else:
            print(f"Warning: Unknown tier '{t}'. Valid tiers: {', '.join(sorted(TOWN_TIERS.keys()))}")
    return towns


class RedfinFetcher:
    def __init__(self, delay=1.5):
        self.delay = delay
        self.session = requests.Session()
        self.session.verify = False
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.9',
            'Accept-Encoding': 'gzip, deflate, br',
            'Sec-Ch-Ua': '"Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"',
            'Sec-Ch-Ua-Mobile': '?0',
            'Sec-Ch-Ua-Platform': '"Windows"',
        })
        self.base = 'https://www.redfin.com/stingray/'
        self._init_session()

    def _init_session(self):
        """Visit Redfin homepage first to establish cookies, then use those for API calls."""
        print("Initializing session (fetching cookies from redfin.com)...")
        try:
            resp = self.session.get('https://www.redfin.com/', timeout=15)
            cookies = len(self.session.cookies)
            print(f"  Got {cookies} cookies, status {resp.status_code}")
        except Exception as e:
            print(f"  Warning: Could not fetch homepage cookies: {e}")
            print("  Continuing anyway — API calls may fail.")

    def _sleep(self):
        time.sleep(self.delay)

    # ===== SEARCH BY TOWN (CSV) =====
    def search_town_csv(self, town_name, min_price=700000, max_price=1400000, min_beds=3):
        """
        Search for listings in a town using Redfin's gis-csv endpoint.
        First resolves the town name to a region_id, then fetches CSV.
        """
        print(f"\n--- Searching: {town_name} (${min_price:,}-${max_price:,}, {min_beds}+ beds) ---")

        # Step 1: Resolve town to region_id via search
        region_id, region_type = self._resolve_region(town_name)
        if not region_id:
            print(f"  Could not resolve region for '{town_name}', skipping.")
            return []

        print(f"  Region ID: {region_id} (type {region_type})")
        self._sleep()

        # Step 2: Fetch CSV
        params = {
            'al': 1,
            'market': 'boston',
            'min_price': min_price,
            'max_price': max_price,
            'num_beds': min_beds,
            'num_homes': 350,
            'ord': 'redfin-recommended-asc',
            'page_number': 1,
            'region_id': region_id,
            'region_type': region_type,
            'sf': '1,2,3,5,6,7',
            'sp': 'true',
            'status': 9,  # active + coming soon
            'uipt': '1,2,3',  # house, condo, townhouse
            'v': 8,
        }

        url = 'https://www.redfin.com/stingray/api/gis-csv'
        csv_headers = {
            'Referer': 'https://www.redfin.com/',
            'Sec-Fetch-Dest': 'empty',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
        }
        try:
            resp = self.session.get(url, params=params, headers=csv_headers, timeout=30)
            if resp.status_code != 200:
                print(f"  CSV fetch failed: HTTP {resp.status_code}")
                return []

            # Parse CSV
            reader = csv.DictReader(io.StringIO(resp.text))
            listings = []
            for row in reader:
                listing = self._parse_csv_row(row, town_name)
                if listing:
                    listings.append(listing)

            print(f"  Found {len(listings)} listings")
            return listings

        except Exception as e:
            print(f"  Error fetching CSV: {e}")
            return []

    def _redfin_api(self, endpoint, params):
        """Make a request to Redfin's stingray API and parse the JSON response."""
        url = self.base + endpoint
        headers = {
            'Referer': 'https://www.redfin.com/',
            'Sec-Fetch-Dest': 'empty',
            'Sec-Fetch-Mode': 'cors',
            'Sec-Fetch-Site': 'same-origin',
        }
        resp = self.session.get(url, params=params, headers=headers, timeout=30)
        resp.raise_for_status()
        # Redfin prefixes JSON responses with {}&&  — strip it
        text = resp.text
        if text.startswith('{}&&'):
            text = text[4:]
        return json.loads(text)

    def _resolve_region(self, town_name):
        """Resolve a town name to a Redfin region_id and region_type."""
        # Extract just the town name (strip ", MA" etc.)
        clean = town_name.split(',')[0].strip()

        # Check hardcoded lookup first (covers all 56 target towns)
        if clean in REDFIN_REGIONS:
            region_id = REDFIN_REGIONS[clean]
            print(f"  Matched '{clean}' → region_id {region_id}")
            return region_id, 6

        # Case-insensitive fallback
        for name, rid in REDFIN_REGIONS.items():
            if name.lower() == clean.lower():
                print(f"  Matched '{clean}' → region_id {rid}")
                return rid, 6

        # If not in our list, try the API as a last resort
        try:
            print(f"  '{clean}' not in known towns, trying API lookup...")
            result = self._redfin_api('do/location-autocomplete', {
                'location': town_name,
                'v': 2,
            })

            if not isinstance(result, dict):
                return None, None

            payload = result.get('payload', {})
            if not isinstance(payload, dict):
                return None, None

            exact = payload.get('exactMatch') or {}
            if isinstance(exact, dict) and exact.get('type') == '6':
                return exact.get('id'), 6

            sections = payload.get('sections', [])
            for section in sections:
                for row in section.get('rows', []):
                    if row.get('type') == '6':
                        return row.get('id'), 6

            print(f"  Warning: No match for '{town_name}'")
            return None, None

        except Exception as e:
            print(f"  API lookup failed: {e}")
            return None, None

    def _parse_csv_row(self, row, town_name):
        """Parse a CSV row into our listing format."""
        try:
            price = int(row.get('PRICE', '0').replace('$', '').replace(',', '') or '0')
            beds = int(row.get('BEDS', '0') or '0')
            baths = float(row.get('BATHS', '0') or '0')
            sqft = int(row.get('SQUARE FEET', '0').replace(',', '') or '0')
            year = int(row.get('YEAR BUILT', '0') or '0')
            lot_str = row.get('LOT SIZE', '0').replace(',', '')
            lot = int(lot_str or '0')  # in sqft
            lot_acres = round(lot / 43560, 2) if lot else 0
            address = row.get('ADDRESS', '')
            city = row.get('CITY', '')
            state = row.get('STATE OR PROVINCE', '')
            zipcode = row.get('ZIP OR POSTAL CODE', '')
            url = row.get('URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)', '')
            dom = int(row.get('DAYS ON MARKET', '0') or '0')
            hoa = row.get('HOA/MONTH', '')
            prop_type = row.get('PROPERTY TYPE', '')
            status = row.get('STATUS', '')
            lat = row.get('LATITUDE', '')
            lng = row.get('LONGITUDE', '')
            oh_start = row.get('NEXT OPEN HOUSE START TIME', '')
            oh_end = row.get('NEXT OPEN HOUSE END TIME', '')

            full_address = f"{address}, {city}, {state} {zipcode}".strip(', ')

            return {
                'address': full_address,
                'shortAddress': address,
                'town': city,
                'state': state,
                'zip': zipcode,
                'price': price,
                'bedrooms': beds,
                'bathsFull': int(baths),
                'bathsHalf': 1 if baths % 1 >= 0.4 else 0,
                'sqft': sqft,
                'yearBuilt': year,
                'lotAcres': lot_acres,
                'url': url if url.startswith('http') else f"https://www.redfin.com{url}" if url else '',
                'daysOnMarket': dom,
                'hoa': hoa,
                'propertyType': prop_type,
                'status': status,
                'lat': lat,
                'lng': lng,
                'openHouseStart': oh_start,
                'openHouseEnd': oh_end,
                # These need to be filled in from detail fetch or manually
                'heatingType': '',
                'centralAir': None,
                'garageSpaces': 0,
                'garageAttached': False,
                'kitchenRating': 50,
                'entertainingRating': 50,
                'renoRating': 50,
                'streetRating': 50,
                'offices': 0,
                'notes': '',
                '_source': 'redfin-csv',
                '_fetched': datetime.now().isoformat(),
            }
        except Exception as e:
            print(f"  Skipping row: {e}")
            return None

    # ===== FETCH FULL DETAILS FOR A SINGLE LISTING =====
    def fetch_detail(self, redfin_url):
        """
        Fetch full property details from a Redfin URL.
        Returns enriched listing data including heating, AC, garage, etc.
        """
        print(f"\n--- Fetching details: {redfin_url} ---")

        try:
            # Step 1: Get property ID from URL
            path = redfin_url.replace('https://www.redfin.com', '')
            initial = self._redfin_api('api/home/details/initialInfo', {'path': path})
            property_id = initial['payload']['propertyId']
            listing_id = initial['payload'].get('listingId', '')
            print(f"  Property ID: {property_id}, Listing ID: {listing_id}")
            self._sleep()

            # Step 2: Get below-the-fold details
            detail_params = {'propertyId': property_id, 'accessLevel': 1}
            if listing_id:
                detail_params['listingId'] = listing_id
            details = self._redfin_api('api/home/details/belowTheFold', detail_params)
            payload = details.get('payload', {})

            # Step 3: Get basic info from above-the-fold / initial
            basic = initial.get('payload', {})

            # Step 4: Parse everything
            listing = self._parse_details(payload, basic, redfin_url)
            print(f"  Got: {listing.get('address', '?')} — ${listing.get('price', 0):,}")
            return listing

        except Exception as e:
            print(f"  Error fetching details: {e}")
            return None

    def _parse_details(self, payload, basic, url):
        """Parse below_the_fold payload into our listing format."""
        # Property details are nested in various places
        pd = payload.get('publicRecordsInfo', {})
        basic_info = pd.get('basicInfo', {})
        tax_info = pd.get('taxInfo', {})

        # Try to get listing-level data
        listing_info = payload.get('listingInfo', {})

        # Amenities and features
        amenities = payload.get('amenitiesInfo', {})
        super_groups = amenities.get('superGroups', [])

        # Parse features from amenity groups
        heating_type = ''
        central_air = None
        garage_spaces = 0
        garage_attached = False

        for sg in super_groups:
            for group in sg.get('amenityGroups', []):
                group_name = group.get('groupTitle', '').lower()
                entries = group.get('amenityEntries', [])
                for entry in entries:
                    name = entry.get('amenityName', '').lower()
                    values = entry.get('amenityValues', [])
                    val = ', '.join(values).lower() if values else ''

                    # Heating
                    if 'heat' in name or 'heating' in name:
                        if 'gas' in val or 'natural gas' in val:
                            heating_type = 'gas'
                        elif 'oil' in val:
                            heating_type = 'oil'
                        elif 'heat pump' in val:
                            heating_type = 'heatpump'
                        elif 'electric' in val:
                            heating_type = 'electric'
                        else:
                            heating_type = 'other'

                    # Cooling / AC
                    if 'cool' in name or 'air cond' in name or 'a/c' in name:
                        if 'central' in val or 'central air' in val:
                            central_air = True
                        elif 'none' in val or 'no ' in val:
                            central_air = False
                        else:
                            central_air = True  # assume yes if mentioned

                    # Garage
                    if 'garage' in name or 'parking' in name:
                        # Try to extract number of spaces
                        nums = re.findall(r'(\d+)', val)
                        if nums:
                            garage_spaces = max(garage_spaces, int(nums[0]))
                        elif 'yes' in val or 'garage' in val:
                            garage_spaces = max(garage_spaces, 1)
                        if 'attached' in val:
                            garage_attached = True
                        if 'detached' in val:
                            garage_attached = False

        # Build listing
        beds = basic_info.get('beds', 0)
        baths = basic_info.get('baths', 0)
        sqft = basic_info.get('sqFt', 0)
        year = basic_info.get('yearBuilt', 0)
        lot = basic_info.get('lotSqFt', 0)
        price = basic_info.get('price', 0)
        address = basic_info.get('fullAddress', '')
        city = basic_info.get('city', '')
        state = basic_info.get('state', '')
        zipcode = basic_info.get('zip', '')

        return {
            'address': address or f"{city}, {state} {zipcode}",
            'town': city,
            'state': state,
            'zip': zipcode,
            'price': price,
            'bedrooms': beds,
            'bathsFull': int(baths),
            'bathsHalf': 1 if baths % 1 >= 0.4 else 0,
            'sqft': sqft,
            'yearBuilt': year,
            'lotAcres': round(lot / 43560, 2) if lot else 0,
            'url': url,
            'heatingType': heating_type,
            'centralAir': central_air,
            'garageSpaces': garage_spaces,
            'garageAttached': garage_attached,
            'kitchenRating': 50,  # manual
            'entertainingRating': 50,  # manual
            'renoRating': 50,  # manual
            'streetRating': 50,  # manual
            'offices': 0,  # manual
            'notes': '',
            '_source': 'redfin-detail',
            '_fetched': datetime.now().isoformat(),
        }

    # ===== ENRICH CSV LISTINGS WITH FULL DETAILS =====
    def enrich_listings(self, listings, max_enrich=10):
        """
        Take CSV listings and fetch full details (heating, AC, garage) for each.
        Rate-limited to be polite. Stops trying after 2 consecutive failures.
        """
        enriched = 0
        consecutive_fails = 0
        for i, listing in enumerate(listings):
            if enriched >= max_enrich:
                print(f"\n  Enriched {enriched} listings (limit reached).")
                break
            if consecutive_fails >= 2:
                print(f"\n  Detail API appears blocked — skipping remaining enrichment.")
                print(f"  (CSV data is still complete. Fill heating/AC/garage in the House Scorer app.)")
                break

            if listing.get('url'):
                self._sleep()
                detail = self.fetch_detail(listing['url'])
                if detail:
                    for key in ['heatingType', 'centralAir', 'garageSpaces', 'garageAttached']:
                        if detail.get(key) not in (None, '', 0, False):
                            listing[key] = detail[key]
                    listing['_source'] = 'redfin-enriched'
                    enriched += 1
                    consecutive_fails = 0
                else:
                    consecutive_fails += 1

        return listings


def main():
    parser = argparse.ArgumentParser(
        description='Fetch Redfin listings for the House Scorer app',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Search a single town
  python redfin_fetcher.py --town "Milton, MA"

  # Search an entire tier (S = Newton, Arlington, Belmont, Milton)
  python redfin_fetcher.py --tier S

  # Search multiple tiers
  python redfin_fetcher.py --tier S A B

  # Mix tiers and individual towns
  python redfin_fetcher.py --tier S --town "Hingham, MA"

  # Search with custom price range
  python redfin_fetcher.py --tier S A --min-price 800000 --max-price 1200000

  # Search multiple towns
  python redfin_fetcher.py --town "Milton, MA" --town "Hingham, MA" --town "Newton, MA"

  # Fetch full details for a specific listing
  python redfin_fetcher.py --url "https://www.redfin.com/MA/Milton/123-Main-St/home/12345"

  # Search towns and auto-enrich top results with full details
  python redfin_fetcher.py --town "Milton, MA" --enrich 5

  # Output to a specific file
  python redfin_fetcher.py --tier S -o s_tier_listings.json

  # List which towns are in each tier
  python redfin_fetcher.py --show-tiers
        """
    )
    parser.add_argument('--town', action='append', help='Town to search (e.g., "Milton, MA"). Can specify multiple.')
    parser.add_argument('--tier', nargs='+', metavar='TIER', help='Fetch all towns in tier(s): S, A, B, C, D, E, F. Can specify multiple.')
    parser.add_argument('--show-tiers', action='store_true', help='Show which towns are in each tier and exit.')
    parser.add_argument('--url', action='append', help='Redfin listing URL to fetch details for. Can specify multiple.')
    parser.add_argument('--min-price', type=int, default=700000, help='Minimum price (default: 700000)')
    parser.add_argument('--max-price', type=int, default=1400000, help='Maximum price (default: 1400000)')
    parser.add_argument('--min-beds', type=int, default=3, help='Minimum bedrooms (default: 3)')
    parser.add_argument('--enrich', type=int, default=0, help='Number of CSV listings to enrich with full details (default: 0)')
    parser.add_argument('--delay', type=float, default=1.5, help='Delay between API requests in seconds (default: 1.5)')
    parser.add_argument('-o', '--output', default='redfin_listings.json', help='Output file (default: redfin_listings.json)')

    args = parser.parse_args()

    # --show-tiers: print tier breakdown and exit
    if args.show_tiers:
        global TOWN_TIERS
        if TOWN_TIERS is None:
            TOWN_TIERS = _load_town_tiers()
        print("\nTown Tiers (from Town Ranker):\n")
        for tier in ['S', 'A', 'B', 'C', 'D', 'E', 'F']:
            towns = TOWN_TIERS.get(tier, [])
            if towns:
                print(f"  {tier} Tier ({len(towns)} towns): {', '.join(towns)}")
        print(f"\n  Total: {sum(len(v) for v in TOWN_TIERS.values())} towns")
        sys.exit(0)

    # Expand --tier into town names
    if args.tier:
        tier_towns = get_towns_for_tiers(args.tier)
        if tier_towns:
            tiers_label = ','.join(t.upper() for t in args.tier)
            print(f"Tier {tiers_label}: {len(tier_towns)} towns — {', '.join(tier_towns)}")
            if not args.town:
                args.town = []
            args.town.extend([f"{t}, MA" for t in tier_towns])

    if not args.town and not args.url:
        parser.print_help()
        print("\nError: Specify at least one --town, --tier, or --url")
        sys.exit(1)

    fetcher = RedfinFetcher(delay=args.delay)
    all_listings = []

    # Fetch by town (CSV search)
    if args.town:
        for town in args.town:
            listings = fetcher.search_town_csv(
                town,
                min_price=args.min_price,
                max_price=args.max_price,
                min_beds=args.min_beds,
            )
            if listings and args.enrich > 0:
                listings = fetcher.enrich_listings(listings, max_enrich=args.enrich)
            all_listings.extend(listings)

    # Fetch by URL (full detail)
    if args.url:
        for url in args.url:
            fetcher._sleep()
            detail = fetcher.fetch_detail(url)
            if detail:
                all_listings.append(detail)

    # Deduplicate by address
    seen = set()
    unique = []
    for l in all_listings:
        key = l.get('address', '') or l.get('url', '')
        if key not in seen:
            seen.add(key)
            unique.append(l)

    # Sort by price
    unique.sort(key=lambda x: x.get('price', 0))

    # Assign IDs for House Scorer
    for i, l in enumerate(unique):
        l['id'] = f"h-{int(datetime.now().timestamp())}-{i}"

    # Write output
    output_path = args.output
    with open(output_path, 'w') as f:
        json.dump(unique, f, indent=2)

    print(f"\n{'='*60}")
    print(f"Done! {len(unique)} listings saved to: {output_path}")
    print(f"{'='*60}")

    # Summary
    if unique:
        prices = [l['price'] for l in unique if l['price']]
        print(f"\nPrice range: ${min(prices):,} - ${max(prices):,}")
        print(f"Towns: {', '.join(sorted(set(l['town'] for l in unique if l['town'])))}")

        # Show upcoming open houses
        with_oh = [l for l in unique if l.get('openHouseStart')]
        if with_oh:
            print(f"\nUpcoming Open Houses ({len(with_oh)}):")
            for l in sorted(with_oh, key=lambda x: x['openHouseStart']):
                oh_start = l['openHouseStart']
                oh_end = l.get('openHouseEnd', '')
                time_str = f"{oh_start}"
                if oh_end:
                    # Try to show just the end time portion
                    time_str += f" — {oh_end}"
                print(f"  {l['shortAddress'] or l['address']:<40s} ${l['price']:>10,}  {time_str}")
        else:
            print("\nNo upcoming open houses found in these listings.")

        # Show what still needs manual input
        needs_manual = [k for k in ['heatingType', 'centralAir', 'garageSpaces']
                        if any(not l.get(k) for l in unique)]
        if needs_manual:
            print(f"\nNote: Some listings still need manual data for: {', '.join(needs_manual)}")
            print("Use --enrich flag to auto-fetch these, or fill them in the House Scorer app.")

    print(f"\nNext step: Open house-scorer.html and click 'Import JSON' to load these listings.")


if __name__ == '__main__':
    main()
